# 企业微信机器人配置示例
# 请将此文件的内容复制到 config.yaml 中的对应位置

# ==================== 企业微信机器人配置 ====================
# 推荐使用机器人方式，更安全、更稳定

# 企业微信机器人配置（推荐使用，替代webhook方式）
WEWORK_CORPID: "ww1234567890abcdef"           # 企业ID - 在企业微信管理后台获取
WEWORK_CORPSECRET: "your_corp_secret_here"    # 应用的凭证密钥 - 在应用管理中获取
WEWORK_AGENTID: "1000001"                     # 应用的AgentId - 在应用管理中获取
WEWORK_TOUSER: "@all"                         # 接收消息的用户，@all表示全部用户

# ==================== 配置获取步骤 ====================
# 1. 登录企业微信管理后台: https://work.weixin.qq.com/
# 2. 进入"应用管理" -> "自建" -> "创建应用"
# 3. 创建应用后，获取以下信息：
#    - 企业ID (CORPID): 在"我的企业" -> "企业信息"中查看
#    - 应用密钥 (CORPSECRET): 在应用详情页面查看
#    - 应用ID (AGENTID): 在应用详情页面查看
# 4. 设置应用的可见范围，确保目标用户可以接收消息

# ==================== 用户配置说明 ====================
# WEWORK_TOUSER 支持以下格式：
# - "@all": 发送给所有用户
# - "user1": 发送给指定用户
# - "user1|user2|user3": 发送给多个指定用户
# - "dept1": 发送给指定部门的所有用户

# ==================== 备选配置（已废弃） ====================
# 如果无法使用机器人方式，可以使用webhook方式作为备选
# 但建议优先使用上面的机器人配置

# 企业微信webhook（已废弃，建议使用上面的机器人方式）
WEWORK_WEBHOOK_URL: ""

# ==================== 配置验证 ====================
# 配置完成后，可以运行以下命令验证配置：
# python3 test_wework_robot.py

# ==================== 注意事项 ====================
# 1. 企业微信机器人需要企业微信账号，个人微信无法使用
# 2. 应用需要设置正确的可见范围，否则用户无法接收消息
# 3. 企业微信API有频率限制，建议合理设置发送间隔
# 4. 保护好应用密钥，不要泄露给他人